import { FATPAPER_LOGIN_URL, MONOPOLY_SERVER_URL, USER_SERVER_PATH, PROTOCOL } from "../global.config";

export const __MONOPOLYSERVER__ = MONOPOLY_SERVER_URL;
export const __USERSERVER__ = USER_SERVER_PATH;
export const __LOGINPAGEURL__ = FATPAPER_LOGIN_URL;
export const __PROTOCOL__ = PROTOCOL;
